# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb3de9ee43cae8c1ca8a66b777c633bff6c71a25c7dfcd322cb3b03ecb47f3a0bf15d79a6ad08d69e00016238fc7235ac3e7ed36670d7ee0f3e28ce11567fa7

test:
  secret_key_base: b273e01a08e98b82406f917a0667228ef517574d9d1f087985d29c2539b80a3700a7f75346addb04be927ae45910f0613da54b95a5db534330558199418e2a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
